import AppKit
import AppleArchive
import CryptoKit
import Foundation
import System

/// Where a background update currently stands. Surfaced in settings so a silent
/// process is still an observable one.
enum UpdateInstallState: Sendable, Equatable {
    case idle
    case downloading
    case verifying
    /// The bundle on disk is already the new version; only a relaunch is left.
    case installed(String)
    case failed(String)
}

/// Downloads a release, verifies who signed it, and replaces Toki's own bundle.
///
/// This is the one place in Toki where a remote file becomes executable code, so the
/// trust anchor is stated plainly: **an Ed25519 public key compiled into this file.**
/// Nothing is written to the bundle until that key has verified the archive
/// byte-for-byte, and the key lives in the binary rather than in a config file or a
/// server response, so neither a tampered `config.json` nor a hostile GitHub response
/// can substitute one.
///
/// Why this is defensible on an ad-hoc-signed app: Apple code signing answers "did
/// Apple's notary see this?", which an ad-hoc build cannot answer at all. The Ed25519
/// signature answers a different and — for self-replacement — sufficient question:
/// "was this archive produced by the holder of the release private key?". That key
/// never enters this repository; see `scripts/make-release-key.swift`.
///
/// What is deliberately *not* claimed: this does not protect against a compromised
/// release key, and it does not roll a bad update back. See SECURITY.md § 잔여 리스크.
enum UpdateInstaller {
    /// Stable asset names, so a new version never needs these edited.
    static let archiveURL = URL(
        string: "https://github.com/osh0678/toki/releases/latest/download/Toki.aar"
    )!
    static let signatureURL = URL(
        string: "https://github.com/osh0678/toki/releases/latest/download/Toki.aar.sig"
    )!

    /// Ed25519 public key, 32 bytes as hex, generated by `scripts/make-release-key.swift`.
    ///
    /// Empty means no release key has been created yet. That is a *safe* state rather
    /// than a broken one: `isConfigured` reads false, automatic installation is skipped
    /// entirely, and the update card falls back to the manual browser download.
    static let releasePublicKeyHex = "991f33450f2f91e77dd27425ff769806e975f06fc4d8bdc14576b168794492f5"

    /// A release archive is ~400KB. The ceiling is generous but finite, so a wrong or
    /// hostile URL cannot stream unbounded data onto the disk.
    private static let maxArchiveBytes: Int64 = 64 * 1024 * 1024
    private static let maxSignatureBytes = 512
    /// Ed25519 signatures are exactly this long; anything else is not one.
    private static let signatureBytes = 64
    private static let timeout: TimeInterval = 60

    enum Failure: LocalizedError, Equatable {
        case keyMissing
        case notABundle
        case bundleNotWritable
        case downloadFailed
        case tooLarge
        case badSignature
        case malformedBundle
        case versionMismatch
        case extractionFailed

        var errorDescription: String? {
            switch self {
            case .keyMissing: "릴리스 서명 키가 설정되지 않았습니다"
            case .notABundle: "앱 번들로 실행 중이 아닙니다"
            case .bundleNotWritable: "앱 위치에 쓸 권한이 없습니다"
            case .downloadFailed: "다운로드에 실패했습니다"
            case .tooLarge: "받은 파일이 너무 큽니다"
            case .badSignature: "서명 검증에 실패했습니다"
            case .malformedBundle: "받은 번들의 형식이 올바르지 않습니다"
            case .versionMismatch: "받은 버전이 기대한 버전과 다릅니다"
            case .extractionFailed: "압축을 푸는 데 실패했습니다"
            }
        }
    }

    // MARK: - Trust anchor

    static var releasePublicKey: Curve25519.Signing.PublicKey? {
        guard let raw = Data(hex: releasePublicKeyHex), raw.count == 32 else { return nil }
        return try? Curve25519.Signing.PublicKey(rawRepresentation: raw)
    }

    /// False until a release key exists. Callers must read this as "do not auto-install".
    static var isConfigured: Bool { releasePublicKey != nil }

    // MARK: - Install

    /// Replaces the running bundle with `update`, leaving this process running on the
    /// old code until someone relaunches it.
    ///
    /// Returns the bundle that was replaced, so the caller can relaunch from it.
    static func install(_ update: AvailableUpdate) async throws -> URL {
        guard let publicKey = releasePublicKey else { throw Failure.keyMissing }
        guard let bundleURL = runningBundleURL() else { throw Failure.notABundle }

        let parent = bundleURL.deletingLastPathComponent()
        guard FileManager.default.isWritableFile(atPath: parent.path) else {
            throw Failure.bundleNotWritable
        }

        // Same volume as the bundle, so the final swap is a rename rather than a copy —
        // the window in which the app exists in neither place is as small as the
        // filesystem can make it.
        let staging = try FileManager.default.url(
            for: .itemReplacementDirectory,
            in: .userDomainMask,
            appropriateFor: bundleURL,
            create: true
        )
        defer { try? FileManager.default.removeItem(at: staging) }

        let archiveFile = try await downloadArchive(into: staging)
        let signature = try await downloadSignature()

        let archiveBytes = try Data(contentsOf: archiveFile, options: .mappedIfSafe)
        guard publicKey.isValidSignature(signature, for: archiveBytes) else {
            throw Failure.badSignature
        }

        let extracted = staging.appending(path: "extracted")
        try FileManager.default.createDirectory(at: extracted, withIntermediateDirectories: true)
        try extract(archiveFile, into: extracted)

        let staged = extracted.appending(path: bundleURL.lastPathComponent)
        try validate(staged, expecting: update.version)

        _ = try FileManager.default.replaceItemAt(bundleURL, withItemAt: staged)
        return bundleURL
    }

    /// Starts the freshly installed copy and exits this one.
    ///
    /// A new instance is requested explicitly: without it LaunchServices sees a running
    /// app with the same bundle identifier and simply activates the old process, which
    /// would leave the update applied on disk but never actually running.
    /// `bundleURL` must be the value `install` returned. Recomputing it from
    /// `Bundle.main` here would be wrong: `replaceItemAt` swaps directories, so by this
    /// point the running process's own bundle has been moved into the staging directory
    /// and removed along with it.
    @MainActor
    static func relaunch(from bundleURL: URL) {
        let configuration = NSWorkspace.OpenConfiguration()
        configuration.createsNewApplicationInstance = true

        NSWorkspace.shared.openApplication(at: bundleURL, configuration: configuration) { _, _ in
            Task { @MainActor in NSApp.terminate(nil) }
        }
    }

    // MARK: - Steps

    /// `Bundle.main.bundleURL` also answers for a bare executable run from the build
    /// directory, where it points at the containing folder. Requiring the `.app`
    /// extension keeps a development run from ever being "updated" over itself.
    private static func runningBundleURL() -> URL? {
        let url = Bundle.main.bundleURL
        return url.pathExtension == "app" ? url : nil
    }

    /// Streamed to disk rather than into memory: `URLSession.download` writes to a file,
    /// so an unexpectedly large response cannot be buffered into RAM first.
    private static func downloadArchive(into staging: URL) async throws -> URL {
        var request = URLRequest(url: archiveURL)
        request.timeoutInterval = timeout

        guard let (temporary, response) = try? await URLSession.shared.download(for: request),
              (response as? HTTPURLResponse)?.statusCode == 200
        else { throw Failure.downloadFailed }

        let attributes = try? FileManager.default.attributesOfItem(atPath: temporary.path)
        guard let size = attributes?[.size] as? Int64, size > 0, size <= maxArchiveBytes else {
            try? FileManager.default.removeItem(at: temporary)
            throw Failure.tooLarge
        }

        let destination = staging.appending(path: "Toki.aar")
        try FileManager.default.moveItem(at: temporary, to: destination)
        return destination
    }

    private static func downloadSignature() async throws -> Data {
        var request = URLRequest(url: signatureURL)
        request.timeoutInterval = timeout

        guard let (data, response) = try? await URLSession.shared.data(for: request),
              (response as? HTTPURLResponse)?.statusCode == 200
        else { throw Failure.downloadFailed }

        guard data.count <= maxSignatureBytes else { throw Failure.tooLarge }
        guard data.count == signatureBytes else { throw Failure.badSignature }
        return data
    }

    /// Apple Archive rather than a zip or a dmg, because it is the only container macOS
    /// can expand through a framework. `unzip`, `ditto`, and `hdiutil` are all
    /// subprocesses, and spawning one here would break the guarantee that Toki launches
    /// exactly one external process from exactly one file (SECURITY.md G3).
    private static func extract(_ archive: URL, into directory: URL) throws {
        guard let source = ArchiveByteStream.fileStream(
            path: FilePath(archive.path),
            mode: .readOnly,
            options: [],
            permissions: FilePermissions(rawValue: 0o644)
        ) else { throw Failure.extractionFailed }
        defer { try? source.close() }

        guard let decompressed = ArchiveByteStream.decompressionStream(readingFrom: source)
        else { throw Failure.extractionFailed }
        defer { try? decompressed.close() }

        guard let decoded = ArchiveStream.decodeStream(readingFrom: decompressed)
        else { throw Failure.extractionFailed }
        defer { try? decoded.close() }

        guard let output = ArchiveStream.extractStream(
            extractingTo: FilePath(directory.path),
            flags: [.ignoreOperationNotPermitted]
        ) else { throw Failure.extractionFailed }
        defer { try? output.close() }

        guard (try? ArchiveStream.process(readingFrom: decoded, writingTo: output)) != nil else {
            throw Failure.extractionFailed
        }
    }

    /// Checks what a signature alone cannot.
    ///
    /// A signature proves the archive is authentic, not that it is the *right* one — a
    /// correctly signed older release, replayed by whoever serves the download, would
    /// otherwise install as an "update". Requiring the staged bundle to declare both the
    /// version the check announced and a version newer than the running one closes that.
    private static func validate(_ bundle: URL, expecting version: String) throws {
        let manager = FileManager.default
        let executable = bundle.appending(path: "Contents/MacOS/Toki")
        let plist = bundle.appending(path: "Contents/Info.plist")

        guard manager.isExecutableFile(atPath: executable.path),
              let data = try? Data(contentsOf: plist),
              let info = try? PropertyListSerialization.propertyList(
                  from: data, options: [], format: nil
              ) as? [String: Any],
              let staged = info["CFBundleShortVersionString"] as? String
        else { throw Failure.malformedBundle }

        guard staged == version,
              UpdateChecker.isNewer(staged, than: UpdateChecker.currentVersion)
        else { throw Failure.versionMismatch }
    }
}

private extension Data {
    /// Parses the compiled-in public key. Returns nil on anything that is not clean hex,
    /// so a mistyped key disables auto-install rather than half-configuring it.
    init?(hex: String) {
        guard hex.count.isMultiple(of: 2) else { return nil }
        var bytes = [UInt8]()
        bytes.reserveCapacity(hex.count / 2)

        var index = hex.startIndex
        while index < hex.endIndex {
            let next = hex.index(index, offsetBy: 2)
            guard let byte = UInt8(hex[index ..< next], radix: 16) else { return nil }
            bytes.append(byte)
            index = next
        }
        self = Data(bytes)
    }
}
